/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  Contracts_extraStorage_sol_ExtraStorage,
  Contracts_extraStorage_sol_ExtraStorageInterface,
} from "../Contracts_extraStorage_sol_ExtraStorage";

const _abi = [
  {
    inputs: [
      {
        internalType: "string",
        name: "_name",
        type: "string",
      },
      {
        internalType: "uint256",
        name: "_favoriteNumber",
        type: "uint256",
      },
    ],
    name: "addPerson",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    name: "nameToFavoriteNumber",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "people",
    outputs: [
      {
        internalType: "uint256",
        name: "favoriteNumber",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "name",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "retrieve",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_favoriteNumber",
        type: "uint256",
      },
    ],
    name: "store",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class Contracts_extraStorage_sol_ExtraStorage__factory {
  static readonly abi = _abi;
  static createInterface(): Contracts_extraStorage_sol_ExtraStorageInterface {
    return new Interface(
      _abi
    ) as Contracts_extraStorage_sol_ExtraStorageInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): Contracts_extraStorage_sol_ExtraStorage {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as Contracts_extraStorage_sol_ExtraStorage;
  }
}
