/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Contracts_extraStorage_sol_ExtraStorage__factory } from "./Contracts_extraStorage_sol_ExtraStorage__factory";
export { Contracts_simpleStorage_sol_SimpleStorage__factory } from "./Contracts_simpleStorage_sol_SimpleStorage__factory";
export { Contracts_storageFactory_sol_StorageFactory__factory } from "./Contracts_storageFactory_sol_StorageFactory__factory";
