/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Contracts_simpleStorage_sol_SimpleStorage__factory } from "./Contracts_simpleStorage_sol_SimpleStorage__factory";
