/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Contracts_simpleStorage_sol_SimpleStorage } from "./Contracts_simpleStorage_sol_SimpleStorage";
export * as factories from "./factories";
export { Contracts_simpleStorage_sol_SimpleStorage__factory } from "./factories/Contracts_simpleStorage_sol_SimpleStorage__factory";
