/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Contracts_extraStorage_sol_ExtraStorage } from "./Contracts_extraStorage_sol_ExtraStorage";
export type { Contracts_simpleStorage_sol_SimpleStorage } from "./Contracts_simpleStorage_sol_SimpleStorage";
export type { Contracts_storageFactory_sol_StorageFactory } from "./Contracts_storageFactory_sol_StorageFactory";
export * as factories from "./factories";
export { Contracts_extraStorage_sol_ExtraStorage__factory } from "./factories/Contracts_extraStorage_sol_ExtraStorage__factory";
export { Contracts_simpleStorage_sol_SimpleStorage__factory } from "./factories/Contracts_simpleStorage_sol_SimpleStorage__factory";
export { Contracts_storageFactory_sol_StorageFactory__factory } from "./factories/Contracts_storageFactory_sol_StorageFactory__factory";
